### PR TITLE
WIP: collation code

### PR DESCRIPTION
**Pull request by JohnAD**
Was just thinking of what functions would be useful to expose for adding the DUCET db (and possible tr10 collation algo) to this repo.

Feel free to ignore. Just playing around with ideas.

### CODE REVIEW

**Comment by JohnAD** [comment]
Thinking about it more, I suspect the actual collation algorithm should be a separate library. This one should limit itself to the data used by the algo.

**Comment by nitely** [comment]
yeah, I think just the table/mappings should live in this repo. I checked the doc a few days ago, the mapping is many runes to many collation elements. Some are not included in the txt and need to be generated (ex: Han, and some korean scripts), and some other unicode data is required for that. I suspect, the collation algo needs to lookup 3 runes, if there is no match, 2 runes, if no match 1 to generate the sort key.

There is a normalization lib in nim btw https://github.com/nitely/nim-normalize

**Comment by nitely** [comment]
I did some work on #30

**Comment by nitely** [comment]
done on #30

**Pull request closed without merging**
